name: "Hello World"
description: "Greet someone with Hello World"
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  random-number:
    description: "A random number"
    value: ${{steps.random-number-generator.outputs.random-id}}
runs:
  using: "composite"
  steps:
    - name: echo Hello ${{inputs.who-to-greet}}.
      run: echo Hello ${{inputs.who-to-greet}}.
      shell: bash
    - name: "Random number generator"
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
    - name: adding path
      run:  echo "${{ github.action_path}}" >> $GITHUB_PATH
      shell: bash
    - name: calling composite
      run:  goodbye.sh
      shell: bash   

